### ISSUE TITLE
[Contibution] es_es translation

### ISSUE THREAD

**Issue by Nekkok** [Goldorion/Enchanter#2]
Hi! I really like your mod, specially farmer and miner put actual use to tools and are original enchantments I haven't seen in other mods. I would like to do my bit with this translation for spanish (Spain) players.

Hope you like it!

https://gist.github.com/kxkxrxtx/f61c2bac0b43088893ad468b58074c13

**Comment by Goldorion** [comment]
Thank you for your contribution!
